### ISSUE TITLE
Ability to debug addin projects.

### ISSUE THREAD

**Issue by matthewrdev** [mhutch/MonoDevelop.AddinMaker#10]
I'd like Addin Maker to allow debugging of addin projects. Currently it fails with the following error:

**Could not load project 'MonoDevelopAddinPackager/MonoDevelopAddinPackager.csproj' with unknown item type '{86F6BF2A-E449-4B3E-813B-9ACC37E5545F}'**

I understand that this could lead to Inception-esq behaviour (each instance of XS being able to launch a new addin in debugging) but it would be very useful in the development of one of my current projects (https://github.com/matthewrdev/monodevelop-addin-packager)

**Comment by mhutch** [comment]
This should work if you install AddinMaker. Can you describe your setup - which which MD instance are debugging which, where and how the addin was installed?

**Comment by matthewrdev** [comment]
@mhutch Thanks for chasing this up, apologies for not getting back to you. This is no longer a requirement for me.
