### ISSUE TITLE
GTK# integration disabled

### ISSUE THREAD

**Issue by stefandevo** [mhutch/MonoDevelop.AddinMaker#14]
When using the AddinMaker, the GTK# integration is disabled.
The project types <ProjectTypeGuids>{86F6BF2A-E449-4B3E-813B-9ACC37E5545F};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids> prevents the project to add a New Dialog for example; the command New Dialog is still there but the AddFile dialog does not show them.
The workaround is to temporarily remove the ProjectTypes from the .proj file, do the integration and re-enable the project types again.

**Comment by mhutch** [comment]
Happy to take patches to fix this, but I don't generally use the GTK# designer myself. I'd recommend XWT for new code.
