### ISSUE TITLE
Unable to build addin maker from command line using monodevelop built from source

### ISSUE THREAD

**Issue by mrward** [mhutch/MonoDevelop.AddinMaker#16]
To repro:

git clone git@github.com:mono/monodevelop.git
cd monodevelop
git checkout roslyn
git submodule update --init --recursive
make
cd ..

git clone https://github.com/mhutch/MonoDevelop.AddinMaker
cd MonoDevelop.AddinMaker
nuget restore MonoDevelop.AddinMaker.sln
make install /p:MDBinDir=../monodevelop/main/build/bin /p:MDProfileVersion=6.0

The build then fails since it seems to find addin dlls from the monodevelop/main/build/test directory.

```
MonoDevelop.AddinMaker/MonoDevelop.Addins.Tasks/bin/Debug/MonoDevelop.Addins.targets: error : Errors found in add-in 'monodevelop/main/build/tests/MonoDevelop.CSharpBinding.dll:
MonoDevelop.AddinMaker/MonoDevelop.Addins.Tasks/bin/Debug/MonoDevelop.Addins.targets: error : The file 'monodevelop/main/build/tests/MonoDevelop.CSharpBinding.Autotools.dll' referenced in the manifest could not be found.
MonoDevelop.AddinMaker/MonoDevelop.Addins.Tasks/bin/Debug/MonoDevelop.Addins.targets: error : The file 'monodevelop/main/build/tests/MonoDevelop.CSharpBinding.AspNet.dll' referenced in the manifest could not be found.
```

I ended up removing the tests directory to resolve this. Just wondering if the tests directory should be excluded.

**Comment by mhutch** [comment]
It's a bug in MonoDevelop, see https://github.com/mono/monodevelop/commit/92ada36d31247e1edfe17ed23a5a0d0f114b6b47

**Comment by mhutch** [comment]
Though @slluis seems to have now reverted the fix, not sure why.

**Comment by slluis** [comment]
The change broke the build, and I didn't want to leave it broken before going to sleep. I'll do a proper fix today.
