### ISSUE TITLE
Duplicate reference in Solution pad

### ISSUE THREAD

**Issue by mrward** [mhutch/MonoDevelop.AddinMaker#20]
With the roslyn build of monodevelop, and the roslyn branch of the addin maker installed, when a reference is added to the project you get a duplicate reference added to the solution pad.
## To repro:
1. Create a C# console app.
2. Double click the References node in the Solution pad to open the Edit References dialog.
3. Select System.Xml and OK the dialog.
## Expected result:

Single System.Xml node in References in the Solution pad.
## Actual result:

Two System.Xml nodes in References.

Debugging this it looks like the addin maker refreshes [all child nodes of the project](https://github.com/mhutch/MonoDevelop.AddinMaker/blob/f9d4a0174f3428205ee5134220bab7acb7d4d7a6/AddinProjectNodeBuilder.cs#L54) when any reference is changed. Whilst MonoDevelop is not expecting this and will [add a new tree node](https://github.com/mono/monodevelop/blob/6ff08cb30a844eee2ea6abdbf5bc50d3b9aab455/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectReferenceFolderNodeBuilder.cs#L117).

Not sure where best to fix this. I guess MonoDevelop could be made more defensive to handle an existing reference. Or maybe the addin maker could only refresh its AddinReferenceFolder, assuming that is all that needs to be refreshed.

**Comment by mhutch** [comment]
Yes, I think it just needs to refresh its folder.
