### ISSUE TITLE
Error installing Addin Maker

### ISSUE THREAD

**Issue by LeoHere** [mhutch/MonoDevelop.AddinMaker#23]
I have just installed Xamarin Studio 5.10.2 (build 65) for Mac. After that I tried to install Addin Maker (1.3.0) and I'm getting the following errors:

Xamarin Studio Add-in Setup Utility
ERROR: The package '::MonoDevelop.Ide v6.0' could not be found in any repository
ERROR: The package '::MonoDevelop.Core v6.0' could not be found in any repository
ERROR: The package '::MonoDevelop.Xml v6.0' could not be found in any repository
ERROR: The package '::MonoDevelop.DesignerSupport v6.0' could not be found in any repository
Not all dependencies could be resolved.

I also tried to download Addin Maker (1.2.1) and install it manually but still getting the same errors.

Any suggestion?

**Comment by CliffCawley** [comment]
I get the same thing. I've got a mostly clean mac with Xamarin Studio installed. Do I also need to install a version of MonoDevelop for it to find the dependencies or something?

**Comment by mhutch** [comment]
I updated the package for 6.0, which is available as an alpha. The addin server shouldn't be serving 1.3.0 down to 5.x clients, not sure why that's happening.

**Comment by abhishekpunj5** [comment]
I get the same error. Is there a work around for this?

**Comment by CliffCawley** [comment]
@mhutch I'm a n00b at using the Add-ins, I'm only doing it because I need to patch an existing addin that was created with it. How do I get the alpha version so I can install in Xamarin Studio?

**Comment by LeoHere** [comment]
You can just download the repo and build it yourself. I did it, and i didn't have much issues.

**Comment by mhutch** [comment]
As a workaround you can download the mpack directly and use the addin manager's option to install from a file:

http://addins.monodevelop.com/Stable/Mac/5.7/MonoDevelop.AddinMaker-1.2.1.mpack

**Comment by abhishekpunj5** [comment]
I tried installing using the 1.2.1 mpack and still got the same error. Its strange that the error message still shows Addin Maker v1.3.0 being installed. Any clues what is going wrong?

I am attaching the screen shot of the error message that pops up.

![error](https://cloud.githubusercontent.com/assets/5646991/13451828/ae0b4706-e068-11e5-972c-e4116fedc1c0.JPG)

**Comment by mhutch** [comment]
I republished 1.2.1 from a new branch and it seems to be working now.
