### ISSUE TITLE
[XS6] Cannot debug on Mac without changing global default .NET runtime preference

### ISSUE THREAD

**Issue by sandyarmstrong** [mhutch/MonoDevelop.AddinMaker#25]
```
XS 6.0 (build 4520)
Addin Maker 1.3.0 installed from gallery
OS: Mac OS X Yosemite
```

(this works fine on Windows)

When debugging an addin project in a default install of XS6, launch of the new XS instance [fails](https://gist.github.com/sandyarmstrong/1f773d57ad997bd8e9db) because it is using the default configured .NET runtime, which is 32-bit. XS6 on Mac now requires 64-bit Mono.

You need to go to `Preferences -> Projects -> .NET Runtimes` and select a 64-bit runtime.

Filing an issue because I'm not sure it makes sense to require this setting globally.

**Comment by mhutch** [comment]
TBH I consider this to be an XS bug. There's no way to mark the app as requiring 64-bit, and if I launch the native stub instead of the exe then debugging won't work.

**Comment by sandyarmstrong** [comment]
Sounds good, I'll close this then.
