### ISSUE TITLE
How to set Addin Icon32

### ISSUE THREAD

**Issue by brianlagunas** [mhutch/MonoDevelop.AddinMaker#34]
I am trying out Addin Maker for the first time and cannot seem to figure out how to set the addin icon.

normally I would do this:

```
<Addin ...>
    <Header>
        <Icon32>...</Icon32>
    </Header>
</Addin>
```

How do I do this with Addin Maker?

**Comment by mhutch** [comment]
I don't think it's currently possible to do this with Mono.Addins attributes /cc @slluis.

**Comment by slluis** [comment]
This should do it:

```
[assembly:AddinProperty ("Icon32","TheIcon.png")]
```

Or you can add an add-in manifest resource with that xml (but using ExtensionModel element as root instead of Addin).
