### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by tzachshabtay** [mhutch/MonoDevelop.AddinMaker#36]
Hi, is there a way for me to integrate building my addin using Travis/Appveyor/Jenkins/etc?

When I naively tried to compile I got:
C:\projects\monoags\packages\MonoDevelop.Addins.0.3.4\build\net40\MonoDevelop.Addins.targets(88,5): error : Bin directory not found: C:\Program Files (x86)\Xamarin Studio\bin

Thanks.

**Comment by mhutch** [comment]
You need a MD/XS build on your CI server to build against. You don't need to install it, you can copy it to a directory and point the tasks at it using the `MDBinDir` property.
