### ISSUE TITLE
Visual Studio For Mac (Preview) - 3rd-party Addin Location

### ISSUE THREAD

**Issue by sushihangover** [mhutch/MonoDevelop.AddinMaker#37]
Is the correct install Addin location(?):

`~/Library/Application Support/VisualStudio-7.0/LocalInstall/Addins
`

Also is there a way to bootstrap the install of the AddinMaker for VS4M since `mdtool.exe` is not available in the install ?

`mdtool.exe.mdb` and `mdtool.xml` are in the bin dir.

```
pwd
/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin
foobar:bin sushi$ ls -l mdtool.*
-rw-r--r--  1 sushi  admin  1847 Nov 16 04:40 mdtool.exe.mdb
-rw-r--r--  1 sushi  admin   123 Nov 16 04:40 mdtool.xml
```

**Comment by markmadlangbayan** [comment]
@sushihangover, were you able to to make some progress on this?  I'm trying to learn how to create an add-in for Visual Studio For Mac.

**Comment by sushihangover** [comment]
@markmadlangbayan `mdtool.exe` is still not available (preview 2), I'm *assuming* this is intentional...

You can manually setup an Addin project w/o using this Addin, this just makes it sooooo much easier ;-). 

If you have never written Addins for Monodevelop/Xamarin Studio, I would recommend writing an Addin for Xamarin.Studio 6.x first using this Addin to setup your project so you understand what is required... 

After that you can create a manual project for VS4M (v7) and reference the required assemblies in your project from the "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin" directory. Buyer beware of course as the Addin API might be in flux sine this is "preview" software....

**Comment by markmadlangbayan** [comment]
@sushihangover Thank you!

**Comment by GDreyV** [comment]
Check this https://mobile.twitter.com/mjhutchinson/status/80230477529972326

**Comment by GDreyV** [comment]
Btw you can use mdtool provided with xamarin 6 to publish plugin for VS4M

**Comment by markmadlangbayan** [comment]
@GDreyV the tweet seems to be removed.

**Comment by GDreyV** [comment]
Let's try once again https://mobile.twitter.com/mjhutchinson/status/802304775299723264

**Comment by markmadlangbayan** [comment]
Awesome!  I got it installed.


Thank you!


________________________________

**Comment by mhutch** [comment]
The install location is `~/Library/Application Support/VisualStudio/7.0/LocalInstall/Addins`, and `mdtool` has been replaced by `vstool`.
