### ISSUE TITLE
Xamarin Studio Addin Maker

### ISSUE THREAD

**Issue by alexrainman** [mhutch/MonoDevelop.AddinMaker#38]
Where is it? I cannot find it anymore.

**Comment by stefan89** [comment]
I am facing the same issue. I can't find the Addin Maker in the Xamarin Studio Add-in Manager (Mac version).

In Visual Studio for Mac it is still available.

**Comment by alexrainman** [comment]
Where did it go?

**Comment by alexrainman** [comment]
In Xamarin Studio Addins manager, use this repository http://addins.monodevelop.com/Stable/Mac/6.1.2/root.mrep

Its the last one that includes Addin Maker.

**Comment by stefan89** [comment]
@alexrainman thanks!

**Comment by mhutch** [comment]
This was an issue in the addin server.
