### ISSUE TITLE
Most types shown as unknown in MonoDevelop

### ISSUE THREAD

**Issue by fogzot** [mhutch/MonoDevelop.AddinMaker#4]
I wanted to have a look at the code and I noted that most of the types related to MonoDevelop DLLs are shown as unknown in the editor. This is because there are no references to the DLLs in the project and while it still builds fine (thanks to the custom msbuild tasks, I suppose) it is a bit annoying. What about referencing the DLLs also from the project?

**Comment by mhutch** [comment]
In theory this shouldn't be a problem because MD uses MSBuild/xbuild to resolve assemblies for code completion. Are there any errors in your logs?

**Comment by fogzot** [comment]
I just run the addin on MD from master and the problem isn't there anymore. I guess you can close this issue.
