### ISSUE TITLE
Consider adding Xwt to the main references of the addins

### ISSUE THREAD

**Issue by Therzok** [mhutch/MonoDevelop.AddinMaker#40]
New UI should be done with Xwt, not gtk-sharp. Consider adding it to the main addin references.

**Comment by mhutch** [comment]
Isn't it already referenced? The build targets already pull in transitive references for referenced addins.

**Comment by Therzok** [comment]
I need to recheck this, don't know why I couldn't see Xwt back then.

**Comment by mhutch** [comment]
Reopen if it's still an issue please 😄

**Comment by Therzok** [comment]
I was trying to use Xwt.Mac and that's not referenced in MD.Ide. Yes, the issue can stay closed.
