### ISSUE TITLE
NuGet package should include Cecil

### ISSUE THREAD

**Issue by garuma** [mhutch/MonoDevelop.AddinMaker#46]
With 0.3.17 the tasks switched to use Cecil directly but do not package it directly or indirectly (instead relying on the transitive dependency of Mono.Addins.CecilReflector at compile-time).

Manually adding Mono.Cecil.dll to the NuGet build\ directory fixes the issue.

**Comment by mhutch** [comment]
Fixed. Had to work around some NuGetizer issues.
