### ISSUE TITLE
When creating VS for Mac extension with AddinMaker, get warning "Found conflicts between different versions of the same dependent assembly"

### ISSUE THREAD

**Issue by nathanielcook** [mhutch/MonoDevelop.AddinMaker#48]
Per the results of [this VS Community issue](https://developercommunity.visualstudio.com/content/problem/65579/when-creating-vs-for-mac-extension-with-addinmaker.html) creating a GitHub issue.

**To reproduce:**
Add the AddinMaker 1.3.7 extension to VS for Mac
Add a new extension project to your solution
Build the new project

**Expected results**
The extension project builds with no warnings or errors

**Actual results**
/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed. (MSB3277) (Foo)
When I build with verbosity set to details:
There was a conflict between "ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" and "ICSharpCode.SharpZipLib, Version=4.84.0.0, Culture=neutral, PublicKeyToken=1b03e6acf1164f73". "ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" was chosen because it was primary and "ICSharpCode.SharpZipLib, Version=4.84.0.0, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" was not. References which depend on "ICSharpCode.SharpZipLib, Version=0.86.0.518, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" [/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/ICSharpCode.SharpZipLib.dll]. /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/ICSharpCode.SharpZipLib.dll Project file item includes which caused reference "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/ICSharpCode.SharpZipLib.dll". ICSharpCode.SharpZipLib References which depend on "ICSharpCode.SharpZipLib, Version=4.84.0.0, Culture=neutral, PublicKeyToken=1b03e6acf1164f73" [/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/4.6.1-api/ICSharpCode.SharpZipLib.dll]. /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/Mono.Addins.Setup.dll Project file item includes which caused reference "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/Mono.Addins.Setup.dll". Mono.Addins.Setup MonoDevelop.Ide MonoDevelop.Core Mono.Addins.Gui /Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/gac/monodoc/1.0.0.0_0738eb9f132ed756/monodoc.dll Project file item includes which caused reference "/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/gac/monodoc/1.0.0.0_0738eb9f132ed756/monodoc.dll". MonoDevelop.Ide MonoDevelop.Core /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MonoDevelop.Ide.dll Project file item includes which caused reference "/Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MonoDevelop.Ide.dll". MonoDevelop.Ide
/Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1980,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed. [/Users/ncook/Insightly/mobile/FooBar/FooBar.csproj]

**Full version info:**
=== Visual Studio Professional 2017 for Mac 
=== Version 7.0.1 (build 24) Installation UUID: 3234d07d-f7a0-4180-b21d-d2c24ed872f6 Runtime: Mono 5.0.1.1 (2017-02/5077205) (64-bit) GTK+ 2.24.23 (Raleigh theme) Package version: 500010001 
=== NuGet === Version: 4.0.0.2323 
=== .NET Core === Runtime: /usr/local/share/dotnet/dotnet SDK: /usr/local/share/dotnet/sdk/1.0.0-preview2-003156/Sdks MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.0.1/lib/mono/msbuild/15.0/bin/Sdks === Xamarin.Profiler 
=== Version: 1.5.4 Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler === Xamarin.Android 
=== Version: 7.3.1.2 (Visual Studio Professional) Android SDK: /Users/ncook/Library/Developer/Xamarin/android-sdk-macosx Supported Android versions: 4.4 (API level 19) 5.0 (API level 21) 5.1 (API level 22) 6.0 (API level 23) 7.0 (API level 24) 7.1 (API level 25) SDK Tools Version: 25.2.5 SDK Platform Tools Version: 25.0.6 SDK Build Tools Version: 25.0.3 Java SDK: /usr java version "1.8.0_102" Java(TM) SE Runtime Environment (build 1.8.0_102-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode) Android Designer EPL code available here: https://github.com/xamarin/AndroidDesigner.EPL 
=== Apple Developer Tools 
=== Xcode 8.3.2 (12175) Build 8E2002 
=== Xamarin.iOS === Version: 10.10.0.36 (Visual Studio Professional) Hash: d2270eec Branch: d15-2 Build date: 2017-05-22 16:30:53-0400 
=== Xamarin.Mac === Version: 3.4.0.36 (Visual Studio Professional) 
=== Xamarin Inspector === Version: 1.2.2 Hash: b71b035 Branch: d15-1 Build date: Fri, 21 Apr 2017 17:57:12 GMT 
=== Build Information 
=== Release ID: 700010024 Git revision: 7ab1ca2ced6f584e56b7a0d4d321d00775cd95c9 Build date: 2017-05-19 05:44:51-04 Xamarin addins: 08d17158f3365beee5e60f67999e607cce4b3f93 Build lane: monodevelop-lion-d15-2 
=== Operating System 
=== Mac OS X 10.12.5 Darwin 16.6.0 Darwin Kernel Version 16.6.0 Fri Apr 14 16:21:16 PDT 2017 root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64 
=== Enabled user installed addins === AddinMaker 1.3.7

**Comment by mhutch** [comment]
This is a Mono/MSBuild issue. This issue is that Mono bundles its own copy of SharpZipLib that's actually older, despite having a newer version number. This conflicts at build time with the SharpZipLib used by AddinMaker. You should be able to ignore the warning safely.

**Comment by mhutch** [comment]
I filed an upstream bug https://bugzilla.xamarin.com/show_bug.cgi?id=59304
