### ISSUE TITLE
Why do Addin-flavored projects only support .NET 4.5 as their target framework?

### ISSUE THREAD

**Issue by natronium** [mhutch/MonoDevelop.AddinMaker#49]
I don't have a lot of experience with .NET or MonoDevelop so I might have missed something, but I couldn't seem to find any explanation for only allowing Addin projects to target .NET 4.5.

For reference, it looks this restriction is set at [AddinProjectFlavor.cs:48](https://github.com/mhutch/MonoDevelop.AddinMaker/blob/7bb919dc470810ccc6ae84d9ab640c98a0769ccd/MonoDevelop.AddinMaker/AddinProjectFlavor.cs#L48), and was first added in commit 18deb69.

**Comment by mhutch** [comment]
That check is only checking the identifier (i.e. ".NETFramework"), not the version.
