### ISSUE TITLE
Find a way to get rid of custom ProjectTypeGuid so VS can open Addin projects

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.AddinMaker#50]
VS refuses to open projects with the AddinMaker ProjectTypeGuid. We should find a different way (such as a capability) to recognize Addin projects such that they can be opened in both VS and VS for Mac.

**Comment by mhutch** [comment]
Fixed in e2dd68b27c50b1ec8ee92251bdd00aae6c6f2dcb
