### ISSUE TITLE
Cannot build IDE Extension project

### ISSUE THREAD

**Issue by momchilstefanov** [mhutch/MonoDevelop.AddinMaker#53]
I'm creating empty new IDE Extension project, then doesn't matter if I update the MonoDevelop.Addins package or not the build fails with "error : Could not resolve addin reference 'MonoDevelop.Core'" and "error : Could not resolve addin reference 'MonoDevelop.Ide'".

I tried rebuilding and updating the add-in registry with vstool setup reg-update and reg-build but this doesn't help.

=== Visual Studio Community 2017 for Mac ===
Version 7.1.5 (build 2) Installation UUID: dbcd7d63-12ef-4166-affa-15f92e4e31a2 Runtime: Mono 5.2.0.224 (d15-3/14f2c81) (64-bit) GTK+ 2.24.23 (Raleigh theme) Package version: 502000224

=== NuGet ===
Version: 4.3.0.2418

=== .NET Core ===
Runtime: Not installed SDK: Not installed MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===
Version: 1.5.5 Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===
Xcode 9.0 (13247) Build 9A235

=== Xamarin.Mac ===
Version: 3.6.3.3 (Visual Studio Community)

=== Xamarin.iOS ===
Version: 11.0.0.0 (Visual Studio Community) Hash: 152b654a Branch: xcode9 Build date: 2017-09-15 02:25:56-0400

=== Xamarin.Android ===
Version: 7.4.5.1 (Visual Studio Community) Android SDK: /Users/mstefanov/Library/Developer/Xamarin/android-sdk-macosx Supported Android versions: 6.0 (API level 23) SDK Tools Version: 24.4.1 SDK Platform Tools Version: 23.0.1 SDK Build Tools Version: 23.0.1 Java SDK: /usr java version "1.8.0_101" Java(TM) SE Runtime Environment (build 1.8.0_101-b13) Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode) Android Designer EPL code available here: https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===
Version: 1.3.1 Hash: cbc48dd Branch: 1.3-release Build date: Thu, 21 Sep 2017 19:52:53 GMT Client compatibility: 1

=== Build Information ===
Release ID: 701050002 Git revision: 7afedcaef8e7542e70e3cf8f9bdb26938b8c0876 Build date: 2017-09-15 08:39:58-04 Xamarin addins: 3262aadf811a18c12eac6742532d052b0139a808 Build lane: monodevelop-lion-d15-3-xcode9

=== Operating System ===
Mac OS X 10.12.6 Darwin 16.7.0 Darwin Kernel Version 16.7.0 Thu Jun 15 17:36:27 PDT 2017 root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===
AddinMaker 1.3.7 Manifest.addin 0.0.0.0

**Comment by germgerm** [comment]
running into the same issue using AddinMaker 1.3.7 in MD 7.1 on ubuntu 16.04

**Comment by momchilstefanov** [comment]
It seems after the latest update of VS for Mac I'm able to build.
@germgerm There is a [Linux specific issue](https://github.com/mhutch/MonoDevelop.AddinMaker/issues/1) you can check.
