### ISSUE TITLE
Too many open files error during _MDResolveAddinReferences

### ISSUE THREAD

**Issue by wjk** [mhutch/MonoDevelop.AddinMaker#55]
When I attempt to build a project using the `MonoDevelop.Addins` nuget package on my MacBook running macOS 10.13.3, it fails with some-odd 295 errors, which all trace back to a "Too many open files" error. Running `ulimit -f unlimited` has no effect. It started doing this a few weeks ago (around the time of the VSMac 7.4 update, I think), before which addin projects compiled without issue. Until this is resolved, no addin project will build, which is a problem for me because I need to compile several addins from source for my projects. Please advise. Thanks!

**Comment by mhutch** [comment]
This is an issue in Mono.Addins, see https://github.com/mono/mono-addins/issues/110 for a workaround
