### ISSUE TITLE
How to install an addin?

### ISSUE THREAD

**Issue by PerfectCarl** [mhutch/MonoDevelop.AddinMaker#7]
I'm trying to install the addin I'm writing and the command `tools/install` doesn't install the addin in monodevelop.

How am I supposed to do it?

**Comment by mhutch** [comment]
Run `xbuild yourproject.csproj /t:CreatePackage` and the MSBuild targets will create an mpack file. You can install this using the "install from file" button in the Addin Manager.

**Comment by CalebMorris** [comment]
Xamarin Studio (v5.9.8) doesn't seem to recognize `.mpack` files (doesn't even show up under all files from `Install From File` browser.

When trying to install by `InstallAddIn` target `mdtool` results in
```
FATAL ERROR [2015-11-01 21:32:32Z]: ICSharpCode.SharpZipLib.Zip.ZipException: Version required to extract this entry not supported (45)
```

Is there some other build format that Xamarin accepts or if there is temporary support missing?
