### ISSUE TITLE
VS4Mac 8.0 Support

### ISSUE THREAD

**Issue by rotorgames** [mhutch/MonoDevelop.AddinMaker#71]
@mhutch When are you going to publish a new version with VS4Mac 8.0 supporting? I just have cloned this repository and built. It works fine with 8.0. You can build it and publish without any changes.

**Comment by mhutch** [comment]
It's been published in the extension gallery for several months. Not sure why it isn't showing up for you. Have you refreshed the gallery? Do any extensions show up at all?

**Comment by rotorgames** [comment]
@mhutch Thank you for a quick answer. I found a strange behavior. After vs updating all unsupported extensions were disabled. I didn't see the disabled AddinMaker and I tried to install this extension from the gallery. It was a surprise for me when I could do it and I saw two the same extensions as installed in the list but the old version was disabled, the new version was installed with a message "This extension contains references to Monodevelop 7.8". 

So, it looks like a bug of VS. VS didn't remove the old disabled extension and allowed to install the new version. 

I removed my compilation of AddinMaker and tried to install a version from the gallery. It was fine. The problem is resolved. Thanks

**Comment by mhutch** [comment]
Ah, that sounds like a bug in the extension engine. Could you please report that on Developer Community?

**Comment by rotorgames** [comment]
@mhutch Sure. 

https://developercommunity.visualstudio.com/content/problem/519193/duplicate-extensions-after-updating-to-vs-80-from.html

**Comment by mhutch** [comment]
Thank you!
