### ISSUE TITLE
Display My projectPad option only for xamarin Forms project

### ISSUE THREAD

**Issue by kalirajanganesan** [mhutch/MonoDevelop.AddinMaker#77]
Hi @mhutch @mrward ,

I want the extend the project pad option for our addin. We have achieved by using the below code. Here We have give the condition as DotnetProject So this option was available  for all Dotnet projects but this addin option was only available for Netstandard XamarinForms project only. For that How can I give the condition?

```
 <Extension path="/MonoDevelop/Ide/Commands">
        <Category _name="UI Kit" id="UIKit">
            <Command
                id="TemplateCommands.CreateNewTemplate"
                _description="Creates a template"
                _label="UI Kit for Xamarin.Forms..."
                defaultHandler="CreateTemplateHandler" />
        </Category>
    </Extension>

     <Extension path="/MonoDevelop/Ide/ContextMenu/ProjectPad">
        <Condition id="Itemtype" value="dotnetproject">
            <SeparatorItem
                id="CreateTemplateSeparator"
                insertafter="MonoDevelop.Ide.Commands.ProjectCommands.Unload"
                insertbefore="MonoDevelop.Ide.Commands.ProjectCommands.CustomCommandList" />
            <CommandItem> id="TemplateCommands.CreateNewTemplate"
                insertafter="CreateTemplateSeparator"
                insertbefore="MonoDevelop.Ide.Commands.ProjectCommands.CustomCommandList" />
        </Condition>
    </Extension>
```

**Comment by mrward** [comment]
I would override the [Update method in your CommandHandler](https://github.com/mono/monodevelop/blob/58cfa46817143efde5fbee67ec9e1c2db1873db7/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs#L611). Then set info.Visible to false if the project is one you do not want to support.

I would probably look at checking the project's Capabilities include `XamarinForms`. The Project class has an IsCapabilityMatch method. For .NET Standard you could check all the target frameworks the project has.

**Comment by kalirajanganesan** [comment]
@mrward  Thank you. it was working
