### ISSUE TITLE
Installation failed on Linux

### ISSUE THREAD

**Issue by Mailaender** [mhutch/MonoDevelop.AddinMaker#8]
![image](https://cloud.githubusercontent.com/assets/756669/7439997/1961dda4-f09a-11e4-83c3-b9fad3a92861.png)

Addin Maker version 1.2.1
Mono version 3.12.1

**Comment by mhutch** [comment]
It's an error from the addin engine - it thinks there's a problem in a different addin. This is likely a packaging or installation issue with the ASP.NET addin.
