### ISSUE TITLE
Build VB.net project on MonoDevelop on Linux ubuntu Os

### ISSUE THREAD

**Issue by MartinCief** [mhutch/MonoDevelop.AddinMaker#9]
I try to build VB.net project on Monodevelop on Linux Ubuntu. Get error:

Could not resolved ( >1 results ) "name dataset"

...

Point on error is in Strongly typed dataset with two datatable in relation ( in second datatable).

When I build project on VS on Windows work fine...

Please help me to resolve....

Thanks!

Martin

**Comment by mhutch** [comment]
I suggest you ask on the mono mailing list, this isn't related to this project.
